In [1]:
import pandas as pd
import numpy as np
import networkx as nx
import toml

In [2]:
demand_path = "../case_studies/stylized_EU/inputs/demand.csv"
generation_availability_path = "../case_studies/stylized_EU/inputs/generation_availability.csv"
generation_path = "../case_studies/stylized_EU/inputs/generation.csv"
scalars_path = "../case_studies/stylized_EU/inputs/scalars.toml"

In [3]:
demand_df = pd.read_csv(demand_path)
generation_availability_df = pd.read_csv(generation_availability_path)  
generation_df = pd.read_csv(generation_path)

with open(scalars_path, 'r') as f:
    scalars = toml.load(f)

value_of_lost_load = scalars['value_of_lost_load']
relaxation = scalars['relaxation']

In [4]:
print(f"Demand {demand_df.shape} Generation Avail {generation_availability_df.shape} Generation {generation_df.shape}")
print(f"Value of lost load: {value_of_lost_load} Relaxation: {relaxation}")

Demand (175200, 3) Generation Avail (525600, 4) Generation (106, 6)
Value of lost load: 3.0 Relaxation: False

## Demand File

In [6]:
demand_df.head()

  location  time_step       demand
0      AUS          1  4464.841992
1      AUS          2  4124.826130
2      AUS          3  3816.906161
3      AUS          4  3526.037135
4      AUS          5  3444.794407

## Generation Availability

In [15]:
generation_availability_df.head()

  location technology  time_step  availability
0      AUS      SunPV          1           0.0
1      AUS      SunPV          2           0.0
2      AUS      SunPV          3           0.0
3      AUS      SunPV          4           0.0
4      AUS      SunPV          5           0.0

In [ ]:

tech_per_location = (
    generation_availability_df
        .groupby('location')['technology']
        .nunique()
        .sort_values(ascending=False)   # optional, just for tidy output
)

# How many different technologies overall (across all locations)?
total_unique_tech = generation_availability_df['technology'].nunique()

print("Technologies per location:\n", tech_per_location, "\n")
print("Total unique technologies across every location:", total_unique_tech)

Technologies per location:
 location
AUS    3
BEL    3
SWI    3
SWE    3
SPA    3
SKO    3
POR    3
POL    3
NOR    3
NED    3
ITA    3
IRE    3
GER    3
FRA    3
FIN    3
DEN    3
CZE    3
BLT    3
BLK    3
UKI    3
Name: technology, dtype: int64

Total unique technologies across every location: 3

In [17]:

tech_lists = (generation_availability_df
              .groupby('location')['technology']
              .unique())        # each element is a NumPy array of tech names
print("Tech lists:\n", tech_lists, "\n")

Tech lists:
 location
AUS    [SunPV, WindOff, WindOn]
BEL    [SunPV, WindOff, WindOn]
BLK    [SunPV, WindOff, WindOn]
BLT    [SunPV, WindOff, WindOn]
CZE    [SunPV, WindOff, WindOn]
DEN    [SunPV, WindOff, WindOn]
FIN    [SunPV, WindOff, WindOn]
FRA    [SunPV, WindOff, WindOn]
GER    [SunPV, WindOff, WindOn]
IRE    [SunPV, WindOff, WindOn]
ITA    [SunPV, WindOff, WindOn]
NED    [SunPV, WindOff, WindOn]
NOR    [SunPV, WindOff, WindOn]
POL    [SunPV, WindOff, WindOn]
POR    [SunPV, WindOff, WindOn]
SKO    [SunPV, WindOff, WindOn]
SPA    [SunPV, WindOff, WindOn]
SWE    [SunPV, WindOff, WindOn]
SWI    [SunPV, WindOff, WindOn]
UKI    [SunPV, WindOff, WindOn]
Name: technology, dtype: object

## Generation df

In [18]:
generation_df.head()

,technology,location,investment_cost,variable_cost,unit_capacity,ramping_rate
0,Coal,CZE,33.75,0.15,400,0.4
1,Coal,GER,33.75,0.15,400,0.4
2,Coal,IRE,33.75,0.15,400,0.4
3,Coal,POL,33.75,0.15,400,0.4
4,Coal,SKO,33.75,0.15,400,0.4

In [22]:
tech_per_location = (
    generation_df
        .groupby('location')['technology']
        .nunique()
        .sort_values(ascending=False)   # optional, just for tidy output
)
print("Technologies per location:\n", tech_per_location, "\n")

total_unique_tech = generation_df['technology'].nunique()
print("Total unique technologies across every location:", total_unique_tech)

Technologies per location:
 location
SKO    8
BLK    7
CZE    7
GER    7
UKI    6
POL    6
FRA    6
IRE    6
SWE    5
SPA    5
AUS    5
BEL    5
FIN    5
DEN    5
BLT    5
POR    4
SWI    4
ITA    4
NED    3
NOR    3
Name: technology, dtype: int64

Total unique technologies across every location: 8